equips/urls.py
from django.urls import path

from django.conf.urls import url

from . import views

app_name = 'equips'
urlpatterns = [
	url(r'signup/$',views.signup,name="signup"),
	path('logout',views.logout,name="logout"),
	path('',views.index,name='index'),
	path('about',views.about,name='about'),
	path('physics',views.physics,name='physics'),
	path('chemistry',views.chemistry,name='chemistry'),
	path('biology',views.biology,name='biology'),
	path('<int:equip_id>/',views.detail,name='detail'),
	path('<int:equip_id>/results/',views.results,name='results'),
	path('<int:equip_id>/add_in_wishlist/',views.add_in_wishlist,name='add_in_wishlist'),
]

pcbinhand/urls.py
from django.contrib import admin
from django.urls import path,include

from equips import views

from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^login/$',auth_views.login,name="login"),
	url(r'^logout/$',auth_views.logout,name="logout"),
	path('signup/',views.signup,name='signup'),
	path('equips/',include('equips.urls')),
    path('admin/', admin.site.urls),
]

equips/models.py
from django.db import models
import datetime
from django.utils import timezone

class EquipInfo(models.Model):
	equip_name = models.CharField(max_length=200)
	equip_dept = models.CharField(max_length=200)
	price_per_head = models.IntegerField(default=0)
	date_added = models.DateTimeField('date added')
	no_in_stock = models.IntegerField(default=0)

	def __str__(self):
		return self.equip_name

	def was_recently_added(self):
		now = timezone.now()
		return now-datetime.timedelta(days=1)<=self.date_added<=now

class Attr(models.Model):
	equipment = models.ForeignKey(EquipInfo,on_delete=models.CASCADE)
	desc = models.CharField(max_length=200)
	in_wishlist = models.IntegerField(default=0)

	def __str__(self):
		return self.desc

equips/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import UserCreationForm

from .models import EquipInfo,Attr

def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username,password=raw_password)
			login(request,user)
			return render(request,'equips/index.html',)
	else:
		form = UserCreationForm()
	return render(request,'signup.html',{'form' : form})

def logout(request):
	return render(request,'registration/logged_out.html',)

def index(request):
	latest_equips_list = EquipInfo.objects.order_by('-date_added')[:5]
	context = {'latest_equips_list' : latest_equips_list}
	return render(request,'equips/index.html',context)

def about(request):
	return render(request,'equips/about.html',)

def physics(request):
	physics_equips_list = EquipInfo.objects.filter(equip_dept__startswith='physics')
	context = {'physics_equips_list' : physics_equips_list}
	return render(request,'equips/pdetails.html',context)

def chemistry(request):
	chemistry_equips_list = EquipInfo.objects.filter(equip_dept__startswith='chemistry')
	context = {'chemistry_equips_list' : chemistry_equips_list}
	return render(request,'equips/cdetails.html',context)

def biology(request):
	biology_equips_list = EquipInfo.objects.filter(equip_dept__startswith='biology')
	context = {'biology_equips_list' : biology_equips_list}
	return render(request,'equips/bdetails.html',context)

def detail(request,equip_id):
	equipment = get_object_or_404(EquipInfo,pk=equip_id)
	return render(request,'equips/detail.html',{'equipment':equipment})

def results(request,equip_id):
	equipment = get_object_or_404(EquipInfo,pk=equip_id)
	return render(request,'equips/results.html',{'equipment':equipment})

def add_in_wishlist(request,equip_id):
	equipment = get_object_or_404(EquipInfo,pk=equip_id)
	try:
		selected_choice = equipment.attr_set.get(pk=request.POST['choice'])
	except(KeyError,Attr.DoesNotExist):
		return render(request,'equips/detail.html',{'equipment':equipment , 'error_message':"You didn't select a choice.", })
	else:
		selected_choice.in_wishlist+=1
		# equipment.no_in_stock-=1
		selected_choice.save()
		# equipment.save()
		return HttpResponseRedirect(reverse('equips:results',args=(equipment.id,)))

equips/templates/equips/about.html
{% load static %}
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'equips/style1.css' %}">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy"/>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<!-- Logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> 
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'equips:index' %}">PCBinHand</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp
						Equipments
					</a>
				</li>
				<li class="">
					<a href="/equips/about">
						<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp
						About
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
						Request Equipment
					</a>
				</li>
				<li class="">
					<a href="{% url 'equips:logout' %}">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
						Logout
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
		</div>

	</div>
		
	</nav>


<img src="{% static "equips/images/Atishay.jpg" %}" height="300" width="300">
<p style="padding-left: 100px">Come and Find all your required Science Equipments here!</p>
<div class="mine">
	<p>Made with <span style="font-size:200%;color:red;">  &hearts;  </span> by Atishay Jain</p>
</div>

equips/templates/equips/bdetails.html
{% load static %}
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy"/>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<!-- Logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> 
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'equips:index' %}">PCBinHand</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp
						Equipments
					</a>
				</li>
				<li class="">
					<a href="/equips/about">
						<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp
						About
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
						Request Equipment
					</a>
				</li>
				<li class="">
					<a href="{% url 'equips:logout' %}">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
						Logout
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
		</div>

	</div>
		
	</nav>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'equips/style1.css' %}">
{% if biology_equips_list %}
	<ul>
		{% for e in biology_equips_list %}
			<li><h1><a href="{% url 'equips:detail' e.id %}">{{e.equip_name}}</a></h1><h3><blockquote>Available In Stock -->  {{e.no_in_stock}}</blockquote></h3></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No Equips are available.</p>
{% endif %}

equips/templates/equips/cdetails.html
{% load static %}
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy"/>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<!-- Logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> 
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'equips:index' %}">PCBinHand</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp
						Equipments
					</a>
				</li>
				<li class="">
					<a href="/equips/about">
						<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp
						About
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
						Request Equipment
					</a>
				</li>
				<li class="">
					<a href="{% url 'equips:logout' %}">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
						Logout
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
		</div>

	</div>
		
	</nav>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'equips/style1.css' %}">
{% if chemistry_equips_list %}
	<ul>
		{% for e in chemistry_equips_list %}
			<li><h1><a href="{% url 'equips:detail' e.id %}">{{e.equip_name}}</a></h1><h3><blockquote>Available In Stock -->  {{e.no_in_stock}}</blockquote></h3></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No Equips are available.</p>
{% endif %}

equips/templates/equips/detail.html
{% load static %}
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy"/>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<!-- Logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> 
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'equips:index' %}">PCBinHand</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp
						Equipments
					</a>
				</li>
				<li class="">
					<a href="/equips/about">
						<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp
						About
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
						Request Equipment
					</a>
				</li>
				<li class="">
					<a href="{% url 'equips:logout' %}">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
						Logout
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
		</div>

	</div>
		
	</nav>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'equips/style.css' %}">
<h1>{{equipment.equip_name}}</h1>
<h3><blockquote>Price Per Head --> {{equipment.price_per_head}}</blockquote></h3>
<ul>
	{% for e in equipment.attr_set.all %}
		<li>{{e.desc}}</li>
	{% endfor %}
</ul><br><br>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'equips:add_in_wishlist' equipment.id %}" method="post">
	{% csrf_token %}
	{% for choice in equipment.attr_set.all %}
		<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
		<label for="choice{{forloop.counter}}">Select this Radio Button and Click on Add_In_Wishlist to put the selected item in cart</label><br><br>
	{% endfor %}
	<input type="submit" value="Add_In_Wishlist">
</form>

equips/templates/equips/index.html
{% load static %}
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy"/>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<!-- Logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> 
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'equips:index' %}">PCBinHand</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp
						Equipments
					</a>
				</li>
				<li class="">
					<a href="/equips/about">
						<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp
						About
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
						Request Equipment
					</a>
				</li>
				<li class="">
					<a href="{% url 'equips:logout' %}">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
						Logout
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
		</div>

	</div>
		
	</nav>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'equips/style1.css' %}">

<a href="/equips/physics"><img src="{% static "equips/images/phyequips.jpg" %}" height="500" width="500" style="padding: 20px;border-color: black;border-width: 10px;"></a>
<a href="/equips/chemistry"><img src="{% static "equips/images/chemequips.jpg" %}" height="500" width="500" style="padding: 20px;border-color: black;border-width: 10px;"></a>
<a href="/equips/biology"><img src="{% static "equips/images/biology.jpg" %}" height="500" width="500" style="padding: 20px;border-color: black;border-width: 10px;"></a>

<p><a href="/equips/physics" style="padding: 0px 200px 0px 180px;">Physics</a></p>
<p><a href="/equips/chemistry" style="padding: 10px 200px 20px 150px;">Chemistry</a></p>
<p><a href="/equips/biology" style="padding: 10px 20px 20px 150px;">Biology</a></p>

<h3><strong>Recently Added Equipments</strong></h3><br>
{% if latest_equips_list %}
	<ul>
		{% for e in latest_equips_list %}
			<li><h4>{{e.equip_name}} <blockquote>{{e.equip_dept}}</blockquote></h4></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No Equips are available.</p>
{% endif %}

<!-- </body> -->

equips/templates/equips/pdetails.html
{% load static %}
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy"/>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<!-- Logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> 
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'equips:index' %}">PCBinHand</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp
						Equipments
					</a>
				</li>
				<li class="">
					<a href="/equips/about">
						<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp
						About
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
						Request Equipment
					</a>
				</li>
				<li class="">
					<a href="{% url 'equips:logout' %}">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
						Logout
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
		</div>

	</div>
		
	</nav>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'equips/style1.css' %}">
{% if physics_equips_list %}
	<ul>
		{% for e in physics_equips_list %}
			<li><h1><a href="{% url 'equips:detail' e.id %}">{{e.equip_name}}</a></h1><h3><blockquote>Available In Stock -->  {{e.no_in_stock}}</blockquote></h3></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No Equips are available.</p>
{% endif %}

equips/templates/equips/results.html
{% load static %}
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy"/>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<!-- Logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> 
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'equips:index' %}">PCBinHand</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp
						Equipments
					</a>
				</li>
				<li class="">
					<a href="/equips/about">
						<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp
						About
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
						Request Equipment
					</a>
				</li>
				<li class="">
					<a href="{% url 'equips:logout' %}">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
						Logout
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
		</div>

	</div>
		
	</nav>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'equips/style.css' %}">
<h1>{{ equipment.equip_name }}</h1>
<h3>Available In Stock --> {{equipment.no_in_stock}}</h3><br>

<ul>
	{% for e in equipment.attr_set.all %}
		<li>In Wishlist --> {{e.in_wishlist}}</li>
	{% endfor %}
</ul>
<a href="{% url 'equips:detail' equipment.id %}">Add In Wishlist Again?</a>

equips/templates/signup.html
{% load static %}
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy"/>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<!-- Logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> 
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'equips:index' %}">PCBinHand</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp
						Equipments
					</a>
				</li>
				<li class="">
					<a href="/equips/about">
						<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp
						About
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'equips:index' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
						Request Equipment
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
						Logout
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
		</div>

	</div>
		
	</nav>

{% block content %}
	<h2>Sign Up</h2>
	<form method="post">
		{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Sign Up</button>
	</form>
{% endblock %}